"""Desktop markdown dossier: ~/Desktop/<TICKER>_Aethelark_Report.md"""

from pathlib import Path

from aethelark_trade.engine.scoring import LAYER_WEIGHTS

LAYER_TITLES = {
    "layer_1_fundamentals": "Layer 1 — Fundamentals",
    "layer_2_macro_gravity": "Layer 2 — Macro Gravity",
    "layer_3_news_velocity": "Layer 3 — News Velocity",
    "layer_4_sector_relativity": "Layer 4 — Sector Relativity",
    "layer_5_insider_conviction": "Layer 5 — Insider Conviction",
    "layer_6_geopolitics": "Layer 6 — Macro Regime",
    "layer_7_supply_chain": "Layer 7 — Supply-Chain Contagion",
}


def render_dossier(result) -> str:
    """Render the full markdown report for a scored ticker."""
    lines = [
        f"# {result.ticker} — Aethelark 7-Layer Dossier",
        "",
        f"**Composite Score:** {result.composite_score}/100 — **{result.verdict}**  ",
        f"**Asymmetry:** {result.asymmetry:.1f} : 1  ",
        f"**Invalidation:** {result.invalidation_level}  ",
        f"**Layer Coverage:** {result.coverage:.0%}  ",
        f"**Generated:** {result.generated_at}",
        "",
        "---",
        "",
        "## Liar Filter",
        "",
        f"**Status:** {result.liar_filter.status}",
        "",
        f"{result.liar_filter.detail}",
        "",
        f"- News sentiment: {result.liar_filter.news_sentiment_pct:.0f}%",
        f"- C-suite net open-market flow "
        f"({result.liar_filter.window_days}d): "
        f"${result.liar_filter.csuite_net_usd:,.0f}",
        "",
        "---",
        "",
        "## Layer Scorecard",
        "",
        "| Layer | Weight | Score | Reading |",
        "| :--- | ---: | ---: | :--- |",
    ]

    for name, layer in result.layers.items():
        title = LAYER_TITLES.get(name, name)
        weight = LAYER_WEIGHTS.get(name, 0.0)
        score = f"{layer.score}" if layer.available else "—"
        lines.append(f"| {title} | {weight:.0%} | {score} | {layer.summary} |")

    unavailable = [n for n, l in result.layers.items() if not l.available]
    if unavailable:
        lines += [
            "",
            "### Data Gaps",
            "",
            "These layers were excluded from the composite rather than scored "
            "as neutral, so the verdict reflects only what could be verified:",
            "",
        ]
        lines += [f"- `{n}` — {result.layers[n].summary}" for n in unavailable]

    if result.errors:
        lines += ["", "### Upstream Errors", ""]
        lines += [f"- `{k}`: {v}" for k, v in result.errors.items()]

    lines += [
        "",
        "---",
        "",
        "*Generated by Aethelark-Trade. Research tool, not investment advice.*",
        "",
    ]
    return "\n".join(lines)


def dossier_path(ticker: str) -> Path:
    return Path.home() / "Desktop" / f"{ticker.upper()}_Aethelark_Report.md"


def write_dossier(result) -> Path:
    path = dossier_path(result.ticker)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_dossier(result), encoding="utf-8")
    return path
